# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Computer Science and all else
tagline:             'Bits and pieces of thoughts'
description:         'on computer science, research and other things interesting'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sumit Asthana
  url:               ''
  email:             asthana.sumit23@gmail.com

# Custom vars
version:             1.0.0
